name: Cassandra.highers
favicon: null
layout_spectrum: 0.72228
typography_spectrum: 0.74
title: Graphic Designer for Hire
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62445075-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#115632'
    - '#211f20'
    - '#16a24b'
    - '#e6e6e8'
    - '#6a6b6d'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
